apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: k8s-node-react
build:
  artifacts:
  - image: xeusteerapat/nginx-react
    context: ./client
    docker:
      dockerfile: ./client/Dockerfile
  - image: xeusteerapat/fastify-server
    context: ./server
    docker:
      dockerfile: ./server/Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
